import { Employee, LeaveRequest, ActivityLog } from './types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-01',
    code: 'EMP-01',
    name: 'Chef Rajesh Sharma',
    phone: '+91 98400 11111',
    avatarInitials: 'RS',
    avatarBg: '#133E33', // Deep forest green
    role: 'Executive Chef',
    outlet: 'Poes Garden',
    shift: 'Evening (15:00-23:00)',
    dutyStatus: 'Clocked In',
    clockIn: '14:45',
    hoursToday: '7.5 hrs',
    joined: '12 Jan 2023',
    email: 'rajesh.sharma@m-fd.luxury',
  },
  {
    id: 'emp-02',
    code: 'EMP-02',
    name: 'Ananya Roy',
    phone: '+91 98400 22222',
    avatarInitials: 'AR',
    avatarBg: '#704214', // Warm cognac brown
    role: 'Head Sommelier',
    outlet: 'Palavakkam',
    shift: 'Evening (15:00-23:00)',
    dutyStatus: 'Clocked In',
    clockIn: '15:00',
    hoursToday: '7 hrs',
    joined: '05 Mar 2022',
    email: 'ananya.roy@m-fd.luxury',
  },
  {
    id: 'emp-03',
    code: 'EMP-03',
    name: 'Vikram Seth',
    phone: '+91 98400 33333',
    avatarInitials: 'VS',
    avatarBg: '#2B3A4A', // Slate navy
    role: 'Floor Captain',
    outlet: 'Poes Garden',
    shift: 'Morning (07:00-15:00)',
    dutyStatus: 'Off Duty',
    clockIn: '06:55',
    hoursToday: '8 hrs',
    joined: '22 Jul 2021',
    email: 'vikram.seth@m-fd.luxury',
  },
  {
    id: 'emp-04',
    code: 'EMP-04',
    name: 'Priya Sundaram',
    phone: '+91 98400 44444',
    avatarInitials: 'PS',
    avatarBg: '#15474A', // Dark teal
    role: "Maître d'",
    outlet: 'Anna Nagar',
    shift: 'Evening (15:00-23:00)',
    dutyStatus: 'Clocked In',
    clockIn: '14:50',
    hoursToday: '7.2 hrs',
    joined: '18 Sep 2022',
    email: 'priya.sundaram@m-fd.luxury',
  },
  {
    id: 'emp-05',
    code: 'EMP-05',
    name: 'Arjun Kapoor',
    phone: '+91 98400 55555',
    avatarInitials: 'AK',
    avatarBg: '#4A3222', // Dark amber umber
    role: 'Line Cook',
    outlet: 'Egmore',
    shift: 'Morning (07:00-15:00)',
    dutyStatus: 'Off Duty',
    clockIn: '07:00',
    hoursToday: '8 hrs',
    joined: '30 Oct 2023',
    email: 'arjun.kapoor@m-fd.luxury',
  },
  {
    id: 'emp-06',
    code: 'EMP-06',
    name: 'Meera Patel',
    phone: '+91 98400 66666',
    avatarInitials: 'MP',
    avatarBg: '#5B21B6', // Deep purple
    role: 'Guest Relations',
    outlet: 'Anna Nagar',
    shift: 'General (10:00-18:00)',
    dutyStatus: 'On Leave',
    clockIn: '-',
    hoursToday: '0 hrs',
    joined: '14 Nov 2022',
    email: 'meera.patel@m-fd.luxury',
  },
  {
    id: 'emp-07',
    code: 'EMP-07',
    name: 'Kavita Menon',
    phone: '+91 98400 77777',
    avatarInitials: 'KM',
    avatarBg: '#831843', // Deep wine
    role: 'Pastry Chef',
    outlet: 'Poes Garden',
    shift: 'Morning (06:00-14:00)',
    dutyStatus: 'Off Duty',
    clockIn: '05:50',
    hoursToday: '8 hrs',
    joined: '10 Feb 2023',
    email: 'kavita.menon@m-fd.luxury',
  },
  {
    id: 'emp-08',
    code: 'EMP-08',
    name: 'Siddharth Rao',
    phone: '+91 98400 88888',
    avatarInitials: 'SR',
    avatarBg: '#1E40AF', // Royal sapphire blue
    role: 'Bar Manager',
    outlet: 'Palavakkam',
    shift: 'Night (18:00-02:00)',
    dutyStatus: 'Scheduled',
    clockIn: '-',
    hoursToday: '-',
    joined: '01 Aug 2023',
    email: 'siddharth.rao@m-fd.luxury',
  },
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'req-01',
    employeeId: 'emp-06',
    employeeName: 'Meera Patel',
    employeeCode: 'EMP-06',
    role: 'Guest Relations',
    outlet: 'Anna Nagar',
    avatarInitials: 'MP',
    avatarBg: '#5B21B6',
    type: 'Annual Leave',
    dates: 'Today (Single Day Planned)',
    reason: 'Family wedding attendance in Bengaluru. Handover given to Priya.',
    status: 'Pending',
    requestedAt: 'Yesterday, 18:30',
  },
  {
    id: 'req-02',
    employeeId: 'emp-03',
    employeeName: 'Vikram Seth',
    employeeCode: 'EMP-03',
    role: 'Floor Captain',
    outlet: 'Poes Garden',
    avatarInitials: 'VS',
    avatarBg: '#2B3A4A',
    type: 'Shift Swap',
    dates: 'Tomorrow Evening Shift',
    reason: 'Requesting swap with Ananya Roy to cover VIP delegation dinner.',
    status: 'Pending',
    requestedAt: 'Today, 08:15',
  },
  {
    id: 'req-03',
    employeeId: 'emp-08',
    employeeName: 'Siddharth Rao',
    employeeCode: 'EMP-08',
    role: 'Bar Manager',
    outlet: 'Palavakkam',
    avatarInitials: 'SR',
    avatarBg: '#1E40AF',
    type: 'Overtime Request',
    dates: 'Friday Night (23:00 - 03:00)',
    reason: 'Special cocktail masterclass and private cellar tasting session.',
    status: 'Pending',
    requestedAt: 'Today, 11:20',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-01',
    timestamp: '15:00',
    employeeName: 'Ananya Roy',
    outlet: 'Palavakkam',
    action: 'Clocked In',
    details: 'Punched in on time for Evening Shift (15:00-23:00)',
    type: 'clock-in',
  },
  {
    id: 'act-02',
    timestamp: '14:50',
    employeeName: 'Priya Sundaram',
    outlet: 'Anna Nagar',
    action: 'Clocked In',
    details: 'Punched in 10 mins early for Maître d’ briefing',
    type: 'clock-in',
  },
  {
    id: 'act-03',
    timestamp: '14:45',
    employeeName: 'Chef Rajesh Sharma',
    outlet: 'Poes Garden',
    action: 'Clocked In',
    details: 'Evening kitchen brigade prep station opened',
    type: 'clock-in',
  },
  {
    id: 'act-04',
    timestamp: '15:00',
    employeeName: 'Vikram Seth',
    outlet: 'Poes Garden',
    action: 'Clocked Out',
    details: 'Completed morning service (8 hrs recorded)',
    type: 'clock-out',
  },
  {
    id: 'act-05',
    timestamp: '14:00',
    employeeName: 'Kavita Menon',
    outlet: 'Poes Garden',
    action: 'Clocked Out',
    details: 'Morning patisserie production completed',
    type: 'clock-out',
  },
  {
    id: 'act-06',
    timestamp: '09:00',
    employeeName: 'Meera Patel',
    outlet: 'Anna Nagar',
    action: 'Leave Logged',
    details: 'Scheduled one-day approved absence',
    type: 'leave',
  },
];

export const ALL_OUTLETS = ['Poes Garden', 'Palavakkam', 'Anna Nagar', 'Egmore'] as const;

export const SHIFT_OPTIONS = [
  'Morning (06:00-14:00)',
  'Morning (07:00-15:00)',
  'General (10:00-18:00)',
  'Evening (15:00-23:00)',
  'Night (18:00-02:00)',
];
